FROM node:16-alpine as builder

WORKDIR /frontend

COPY . .

RUN npm ci

RUN npm run build

# Build static assets with nginx
FROM nginx:1.21.0-alpine as production

ENV NODE_ENV production

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /frontend/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
